# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

variables:
  tag: '$(Build.SourceVersion)'
  ImageName: 'hw-python'
  azureSubscription: HKI-kanslia-standalone
  appName: hw-python
  containerRegistry: registry.hub.docker.com

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  displayName: Build the docker image
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'hw-python'

- script: 
    docker tag $(ImageName):latest helsinki/$(ImageName):latest
  displayName: Do image retagging for helsinki repo

- task: Docker@2
  displayName: Push image to Docker hub
  inputs:
    containerRegistry: Docker hub hw-python
    repository: helsinki/$(ImageName)
    command: push
    tags: |
      latest
      $(tag)

      - task: oc-cmd@2
        displayName: Add OC tag to latest image
        inputs:
          openshiftService: Azure OpenShift-hw-python
          cmd: 'tag docker.io/helsinki/hw-python:$(tag) hw-python:latest'
